version: '3.4'

services:
  microservice_template.web:
    image: ${DOCKER_REGISTRY-}microservice_template_web
    container_name: microservice_template_web
    build:
      context: .
      dockerfile: Web/Dockerfile
    ports:
      - 5000:8080
      - 5001:443
    depends_on:
      - microservice_template.db

  microservice_template.db:
    image: postgres
    container_name: microservice_template_db
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./files/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
